#spring:
#  config:
#    activate:
#      on-profile: "qa"
#
build:
  version: "2.0"

accounts:
  message: "ELO QA"
  contactDetails:
    name: "Damian Marc - QA Dev"
    email: "damianmar17@outlook.com"
  onCallSupport:
    -(153)234-5432
    -(153)643-8245